FROM python:3.11-slim

WORKDIR /app

RUN useradd -m appuser

COPY equirements.txt .

RUN pip install --no-cache-dir flash

COPY . .

RUN chown -R appuser:appuser /app

EXPOSE 5000

CMD ["python", "python.py"]