FROM python:3.11-slim

WORKDIR /app

RUN useradd -m appuser

COPY requirements.txt .

RUN chown -R appuser:appuser /app

USER appuser

# Create virtual environment as appuser
RUN python -m venv /home/appuser/venv

# Use the virtual environment
ENV PATH="/home/appuser/venv/bin:$PATH"

# Install packages as appuser
RUN pip install --no-cache-dir -r requirements.txt

COPY --chown=appuser:appuser . .

EXPOSE 5000

CMD ["python", "python.py"]