name: DevSecOps End To End Pipeline

on:
    workflow_dispatch:

jobs:
    # CI (continous Integration Security Scanning)
    Code-Quality:
       uses: ./.github/workflows/code-quality.yml

    Secrets-Scan:
       uses: ./.github/workflows/secrets-scan.yml

    Dependency-Scan:
        uses: ./.github/workflows/dependency-scan.yml

    Docker-Scan:
        uses: ./.github/workflows/docker-lint.yml
    
    # Build once the security scan are complete 
    build:
        needs: [Code-Quality, Secrets-Scan, Dependency-Scan, Docker-Scan]
        uses: ./.github/workflows/docker-build-push.yml
        secrets: inherit

    trivy:
        needs: [build] 
        uses: ./.github/workflows/image-scane.yml
        secrets: inherit
        
    #Deploy to Production
    deploy:
        needs: [trivy]
        uses: ./.github/workflows/deploy-to-server.yml
        secrets: inherit


