name: Conditionals Demo

on: [push, pull_request]

jobs:
  conditional-job:
    if: github.event_name == 'push'
    runs-on:  ubuntu-latest
    steps:
      - name: Only on main
        if: github.ref == 'refs/head/main'
        run: echo "This is main branch"

      - name: This might fail
        id: risky-step
        run: exit 1
        continue-on-error: true

      - name: Run only if previous step failed
        if: failure()
        run: echo "Previous step failed, handling it here"
