name: Upload Artifact Demo

on: push

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a report file
        run: |
          echo "Test Report - $(date)" > repot.txt
          echo "All check passed" >> report.txt

      - name: Upload artifact
        uses: actions/uplaod-artifact@v4
        with:
          name: test-report
          path: report.txt
